### ISSUE TITLE
EBOOT art links are dead

### ISSUE THREAD

**Issue by khatharr** [jurassicplayer/EbootCK#1]
Hey, sorry to contact you here about this, but I wasn't sure where to reach you. I was wondering if you still had your collection of EBOOT art. Whatever image/file host you were using on gbatemp appears to have died. If it's not too much trouble, I'd really appreciate it if you could upload your collection somewhere.

Thanks either way.

**Comment by jurassicplayer** [comment]
I was originally using ye olde filetrip. As for the collection of eboot resources, surprisingly enough someone asked for one of them or something ages ago, so I actually have a MEGA linking to all the ones that I made. It's at the very bottom of the original post. All of the youtube previews still work, so if you want to have a look before you download literal megabytes of data ¯\_(ツ)_/¯.

For convenience though: https://mega.nz/#F!YIklRQ5I!fb_HkySYsshIdaTaoqXV0w

**Comment by khatharr** [comment]
You're the best!
