### ISSUE TITLE
Outdated Code, can't install older versions of PyQT required for this

### ISSUE THREAD

**Issue by DNSDies** [jurassicplayer/EbootCK#2]
QtWebKit has been deprecated for some time now, and older versions of PyQT aren't available to make this work anymore.
Any chance you'll update this?

**Comment by jurassicplayer** [comment]
Apparently I imported QtWebkit for uh...well nothing. I didn't use it.
At the moment, after removing the import, it seems to be working for me (I run Arch, so more likely than not, my packages are probably mostly recent).

I don't actually know if anyone aside from myself will actually be able to make sense of how to use it. If you are just going to use it for previews, it should be good enough to have ffmpeg and the at3tool.exe.

If the program makes no sense, just tell me what you are hoping to accomplish and I can try to help you out with getting there.

**Comment by DNSDies** [comment]
Yeah, I'm on windows, and with the removal of QtWebKit, it's now giving errors about QtWebWidgets, which was replaced with QtWebEngineWidgets

I installed PyQT5, PyQt-sip and PyQtWebEngine
```

Traceback (most recent call last): EbootCK.py", line 8, in <module> from PyQt5 import QtCore, QtGui, uic, QtWebKitWidgets
ImportError: DLL load failed while importing QtWebKitWidgets: The specified module could not be found.

```
I tried removing the code for that, but I'm not good at coding and there are references to modules it provides further in like QtWebKitWidgets.QWebView, QtWidgets.QDesktopWidget().screenGeometry, etc.

It just plain doesn't even work on windows with python anymore. I understand if you don't want to support this after 6+ years, but it's a great all-in-one tool for making nice eboots.

**Comment by jurassicplayer** [comment]
Alright, it should work now (tested and fixed most of it with a Windows install that I never touch). Give it a shot and if it still doesn't work, just tell me what went wrong and I'll see what I can do.

**Comment by DNSDies** [comment]
It seems to be working perfectly now.
Tested it on a fresh python install and seems to work great. Got the GUI at the very least.
If I were you I'd update the readme to note that it require Python 3.8 or greater, PyQT5 and PyQtWebEngine

Thank you again for updating this!
